[general]
show_welcome = false
skip_boot_anim = false
screenshot_dir = "/home/deck/xemu-performance/pr30-disk-assets-live/workspace/Results/20261005-142942972-e074cdb181534311bb9a5b7f839d5d18/screenshots"
[input]
auto_bind = false
background_input_capture = true
[input.bindings]
port1_driver = 'usb-xbox-gamepad'
port1 = '0600cc4158656d752052756e6e657200'
[input.virtual_ports]
port1_connected = 1
port2_connected = 0
port3_connected = 0
port4_connected = 0
[display]
renderer = 'VULKAN'
[display.window]
startup_size = '1280x720'
vsync = false
[audio]
use_dsp_jit = true
[sys]
mem_limit = '64'
[sys.files]
bootrom_path = '/home/deck/xemu-performance/pr30-disk-assets-live/workspace/DiskAssets/pr73-deck-bootrom-e99e3a-v1/disk.qcow2'
flashrom_path = '/home/deck/xemu-performance/pr30-disk-assets-live/workspace/DiskAssets/pr73-deck-flashrom-1de4c8-v1/disk.qcow2'
eeprom_path = '/home/deck/xemu-performance/pr30-disk-assets-live/workspace/Runtime/20261005-142942972-e074cdb181534311bb9a5b7f839d5d18/eeprom.bin'
hdd_path = '/home/deck/xemu-performance/pr30-disk-assets-live/workspace/Runtime/20261005-142942972-e074cdb181534311bb9a5b7f839d5d18/hdd.qcow2'
dvd_path = '/home/deck/xemu-performance/pr30-disk-assets-live/workspace/DiskAssets/conker-usa-readonly-v1/disk.qcow2'
[perf]
cache_shaders = false
